branches:
  only:
  - master

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda36-x64

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda update -q conda
  - conda info -a

install:
  - if "%PYTHON_VERSION%"=="2.7" ( conda create -q -n testenv python=%PYTHON_VERSION% numpy pyqt enum34 six scipy matplotlib)
  - if "%PYTHON_VERSION%"=="3.6" ( conda create -q -n testenv python=%PYTHON_VERSION% numpy pyqt six scipy matplotlib)
  - activate testenv

build: off

test_script:
  - python -m unittest discover tests
